### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by Aaroneisele55** [hugobloem/M5Stack_HomeControl#6]
Hello,
How can I use this with my Home Assistant?
There was an announcement that a guide would be published, but it wasn't published for 2 years.
Can anyone that maybe got this to work or has info on how to set this up can help me?

I think this repo (and project also) got abandoned in a "beta" or "early release" state and won't be updated anymore.

Thanks
Aaron

**Comment by hugobloem** [comment]
Hi Aaron,

That is correct. I juggled with this idea but abandoned it. There are a few reasons. First, micropython on the ESP32 and the LVGL graphics library turned out to be relatively slow. I feel like that setup is better suited for prototyping rather than for a useable device. Second, the battery life of the M5Stack is short, requiring to either keep it charged all the time, or introduce code optimalisations which would be hard to do in micropython due to the expensive interpreter. 

If you want to continue with this, you can! I am not sure how I did it exactly as I remember getting it up and running proved quite hacky. However this will be a great place to start: https://docs.micropython.org/en/latest/esp32/tutorial/intro.html 

Hope this helps,
Hugo

**Comment by hugobloem** [comment]
I forgot to add, since the inception of this project other projects have caught up with M5 Core2 support. ESPhome now supports it as does openHASP. These may be easier to set up and fulfil your requirements. Lastly, I am actively working on a speech recognition home assistant device over here: https://github.com/hugobloem/esp-ha-speech
